create database industry;

use industry;

Select
	*
from employees;

-- 

-- PRODUCT TABLE

CREATE TABLE PRODUCTS(
	PRODUCT_ID INT PRIMARY KEY,
    PRODUCT_NAME VARCHAR(20),
    CATEGORY VARCHAR(20)
);

-- EMPLOYEE TABLE
CREATE TABLE EMP(
	EMP_ID INT PRIMARY KEY,
    EMP_NAME VARCHAR(30),
    SALARY INT,
    CITY VARCHAR(20)
);



CREATE TABLE ORDERS(
	ORDER_ID INT PRIMARY KEY,
    PRODUCT_ID INT,
    EMP_ID INT,
    ORDER_DATE DATE,
    QUANTITY int,
    FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCTS(PRODUCT_ID),
    FOREIGN KEY (EMP_ID) REFERENCES EMP(EMP_ID)
);
    
-- FOREIGN KEYS WITH NAME


CREATE TABLE ORDERS(
	ORDER_ID INT PRIMARY KEY,
    PRODUCT_ID INT,
    EMP_ID INT,
    ORDER_DATE DATE,
    QUANTITY int,
    CONSTRAINT FK_PRODUCT_ID FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCTS(PRODUCT_ID),
    CONSTRAINT FK_EMP_ID FOREIGN KEY (EMP_ID) REFERENCES EMP(EMP_ID)
);


-- REFERENTIAL INTIGRITY

SELECT * FROM EMP;
SELECT * FROM PRODUCTS;


INSERT INTO EMP VALUES
(101,"NEHA",30000,"DELHI"),
(102,"ROHIT",40000,"PUNE"),
(103,"RISHABH",35000,"DELHI"),(
104,"AADITYA",36000,"MUMBAI");

INSERT INTO PRODUCTS VALUES
(1001,"MONITOR","GADGET"),
(1002,"KEYBOARD","GADGET"),
(1003,"CHAIR","FURNITURE");

INSERT INTO ORDERS VALUES(1,1001,101,"2026-08-02",2),(2,1003,103,"2026-08-03",4);

SELECT * FROM ORDERS;





-- EMP_ID 101 --- 110
-- PRODUCT_ID 1001 --- 1020
