-- Subqueries 

-- Query in Query

use company;


select * from employees;

-- SUBQUERY EXECUTES BOTTOM TO TOP


-- Select the employee, those having salary greater than avg salary

-- SCALER SUBQUERY


SELECT
	*
FROM EMPLOYEES
WHERE SALARY > 
	(SELECT
		AVG(SALARY)
	FROM EMPLOYEES);


-- EMPLOYEE WITH HIGHEST SALARY
SELECT
	*
FROM EMPLOYEES
ORDER BY SALARY DESC
LIMIT 1 ;


SELECT
	*
FROM EMPLOYEES
WHERE 
SALARY = (SELECT MAX(SALARY) FROM EMPLOYEES);



-- IN, ANY, ALL

-- SELECT THE RECORDS OF EMPLOYEES IN DEPARTMENT WHERE THE CITY SHOULD BE DELHI

-- EMPLOYEES WORKING IN DEPARTMENT THAT HAVE AT LEAST ONE EMPLOYEE LOCATED IN DELHI.
SELECT
	EMP_NAME,DEPARTMENT,CITY
FROM EMPLOYEES
WHERE DEPARTMENT IN
	(SELECT
		DEPARTMENT
	FROM EMPLOYEES
	WHERE CITY = "DELHI");

-- CORELATED SUBQUERY

-- SELECT THE EMPLOYEES WHOSE SALARY IS GREATER THE AVG SALARY OF HIS/HER DEPARTMENT.

SELECT 
	E1.EMP_NAME,E1.DEPARTMENT,E1.SALARY
FROM EMPLOYEES E1
WHERE E1.SALARY > 
	(SELECT
		AVG(E2.SALARY)
	FROM EMPLOYEES E2
    WHERE E1.DEPARTMENT = E2.DEPARTMENT);



-- EXISTS

-- EXISTS CHECKS WHETHER THE SUBQUERY RETURNS AT LEAST ROW

-- RETURN EMPLOYEES WHOSE DEPARTMENT HAST AT LEAST ONE EMPLOYEE EARNING MORE THAN 150000
SELECT
	E1.EMP_NAME,
    E1.DEPARTMENT,
    E1.SALARY
FROM EMPLOYEES E1
WHERE EXISTS
	(SELECT
		EMP_NAME
	FROM EMPLOYEES E2
		WHERE E2.DEPARTMENT = E1.DEPARTMENT
		AND E2.SALARY > 160000)
ORDER BY E1.SALARY DESC;

-- GET ALL THE EMPLOYEES THOSE ARE EARNING MORE THAN ANY EMPLOYEE OF PUNE

SELECT
	*
FROM EMPLOYEES
WHERE SALARY > ANY (SELECT SALARY FROM EMPLOYEES WHERE CITY ="PUNE");

-- GET ALL THE EMPLOYEES THOSE ARE EARNING MORE THAN ALL EMPLOYEES OF PUNE
SELECT
	*
FROM EMPLOYEES
WHERE SALARY > ALL (SELECT SALARY FROM EMPLOYEES WHERE CITY ="PUNE");


-- SUBQUER IN FROM STATEMENT

SELECT
	DEPARTMENT,
    AVG_DEPARTMENT
FROM
	(SELECT 
		DEPARTMENT,
		AVG(SALARY) AVG_DEPARTMENT
	FROM EMPLOYEES
	GROUP BY DEPARTMENT)t
where avg_department > 90000;



-- subquery inside select
-- show company's average along all the employees records

select
	emp_name,
    salary,
    (select avg(salary) from employees) as avg_salary
from employees;




-- find the employees having maximum salary in their department
select
	emp_name,
    salary,
    department
from employees
where (department,salary) in 
	(select
		department,
		max(salary) max_salary
	from employees
    group by department);
    
    
    
    