-- CRUD

-- Create
-- Read
-- Update
-- Delete

-- 
USE SONIX;

SELECT 
	*
FROM EMPLOYEE;

-- ============================================
--           CREATE OPERATION
-- ============================================


-- SYNTAX OF CREATING TABLE
CREATE TABLE DEPARTMENT(
	DEPT_ID INT,
    DEPT_NAME VARCHAR(10),
    NO_PROJECT INT
);


-- INSERT ROWS/RECORDS IN TABLE
INSERT INTO DEPARTMENT VALUES(101,'FINANCE',3);


-- TO INSERT MULTIPLE RECORDS
INSERT INTO DEPARTMENT VALUES
(102,'IT',5),
(103,'HR',6),
(104,'SALES',9),
(105,'OPERATIONS',2);


-- ================================================
--                  READ OPERATION
-- ================================================


SELECT 
	* -- SELECT ALL THE COLUMNS FROM TABLE
FROM DEPARTMENT;


-- TO PICK SPECIFIC COLUMNS
SELECT
	DEPT_ID,
    NO_PROJECT
FROM DEPARTMENT;


-- TO PICK SPECIFIC NUMBER OF ROWS FROM TABLE
SELECT
	*
FROM DEPARTMENT
LIMIT 3;



-- TO PICK SPECIFIC COLUMNS AND ROWS 
SELECT 
	DEPT_NAME,
    NO_PROJECT
FROM DEPARTMENT
LIMIT 4;



-- ================================================
--                  UPDATE OPERATION
-- ================================================


SELECT * FROM DEPARTMENT;

UPDATE DEPARTMENT
SET NO_PROJECT = 5
WHERE DEPT_ID = 101;

SET SQL_SAFE_UPDATES = 0;

UPDATE DEPARTMENT
SET NO_PROJECT = 3;




-- ================================================
--                  DELETE OPERATION
-- ================================================

SELECT * FROM DEPARTMENT;


DELETE FROM DEPARTMENT
WHERE DEPT_ID = 104;


DELETE FROM DEPARTMENT
WHERE DEPT_ID = 101;

INSERT INTO DEPARTMENT VALUES(101,'FINANCE',3);


-- RENAME


SELECT * FROM DEPARTMENT;
-- USE WHEN ONLY WANT TO CHANGE THE COLUMN NAME
ALTER TABLE DEPARTMENT
RENAME COLUMN DEPT_NAME TO DEPARTMENT ;


-- USE WHEN YOU WANT TO CHANGE THE DATA TYPE AND COLUMN NAME
ALTER TABLE DEPARTMENT 
CHANGE DEPARTMENT DEPARTMENT_NAME VARCHAR(20);



-- DROP TABLE 

DROP TABLE EMPLOYEE;


DROP TABLE IF EXISTS DEPARTMENT;



-- RENAME THE TABLE

SELECT * FROM DEPARTMENT;


RENAME TABLE DEPARTMENT TO DEPT;

-- RENAME/MOVE

CREATE DATABASE ASIX;


-- TO MOVE THE TABLE FROM ONE DATABASE TO ANOTHER DATABASE
RENAME TABLE
SONIX.DEPT TO ASIX.DEPARTMENT;

-- DROP DATABASE 

DROP DATABASE SONIX;


