-- CTE (Common Table expression)

USE STORE;

SELECT
	COUNT(*) RECORDS
FROM SALES
WHERE QUANTITY >
	(SELECT 
		AVG(QUANTITY) AVG_QUANTITY
	FROM SALES);
    
    
-- SOLVING USING CTE
WITH AVG_QUANTITY AS(
	SELECT
		AVG(QUANTITY) AVG_QTY
	FROM SALES
)
SELECT
	*
FROM SALES
WHERE QUANTITY > (SELECT AVG_QTY FROM AVG_QUANTITY);


-- CTE WORKS TOP -> BOTTOM


-- SINGLE CTE
-- DISPLAY ALL THE RECORDS OF ELECTRONICS
WITH CTGR AS
(
	SELECT 
		*
	FROM PRODUCTS
    WHERE CATEGORY = "FURNITURE"
)
select 
	C.product_id,
    C.price,
    S.QUANTITY,
	C.PRICE * S.QUANTITY "SALE"
from CTGR C
INNER JOIN SALES S
ON C.PRODUCT_ID = S.PRODUCT_ID;



-- MULTIPLE CTE
-- CUSTOMER DETAIL WITH ELECTRONICS SALES.

WITH CTGR_DETAIL AS (
	SELECT
		*
	FROM SALES
    WHERE PRODUCT_ID IN(
		SELECT
			PRODUCT_ID 
		FROM PRODUCTS 
		WHERE CATEGORY = "ELECTRONICS")
),
CUSTOMER_DETAILS AS(
	SELECT
		CUSTOMER_ID,
		CUSTOMER_NAME
	FROM CUSTOMERS
)
SELECT
	*
FROM 
CTGR_DETAIL CD
INNER JOIN CUSTOMER_DETAILS CUS
ON CD.CUSTOMER_ID = CUS.CUSTOMER_ID;





-- CTE WITH AGGREATION

-- TOTAL QUANTITY PURCHASED BY EACH CUSTOMER

WITH CUSTOMER_SALES AS(
	SELECT
		CUSTOMER_ID,
        SUM(QUANTITY) TOTAL_QTY
	FROM SALES
    GROUP BY
    CUSTOMER_ID
)
SELECT
	*
FROM CUSTOMER_SALES;


-- CTE WITH JOIN
-- SHOW CUSTOMER NAME AND PRODUCT PURCHASED

WITH SALES_DATA	AS(
	SELECT 
		S.CUSTOMER_ID,
        C.CUSTOMER_NAME,
        P.PRODUCT_NAME,
        S.QUANTITY,
        P.PRICE * S.QUANTITY SALE_AMOUNT
	FROM SALES S
    INNER JOIN PRODUCTS P
    ON P.PRODUCT_ID = S.PRODUCT_ID
    INNER JOIN CUSTOMERS C
    ON C.CUSTOMER_ID = S.CUSTOMER_ID
)

SELECT 
	*
FROM SALES_DATA
WHERE SALE_AMOUNT>100000;



-- NESTED CTE
-- CUSTOMERS WHOSE TOTAL QUANTITY IS ABOVE AVERAGE

WITH CUSTOMER_SALES AS(
	SELECT 
		CUSTOMER_ID,
        SUM(QUANTITY) AS TOTAL_QTY
	FROM SALES
    GROUP BY CUSTOMER_ID
),
AVG_QTY AS (
	SELECT 
		AVG(QUANTITY) AVG_QUANTITY
	FROM SALES
)
SELECT
	CS.CUSTOMER_ID,
    C.CUSTOMER_NAME,
    CS.TOTAL_QTY
FROM CUSTOMER_SALES CS
INNER JOIN CUSTOMERS C
ON C.CUSTOMER_ID = CS.CUSTOMER_ID

WHERE TOTAL_QTY > (SELECT AVG_QUANTITY FROM AVG_QTY);



-- VIEWS


CREATE VIEW ELECTRONICS_DETAILS AS(
	SELECT 
			S.CUSTOMER_ID,
			P.PRODUCT_NAME,
			S.QUANTITY,
			P.PRICE * S.QUANTITY SALE_AMOUNT
	FROM SALES S
	INNER JOIN PRODUCTS P
	ON P.PRODUCT_ID = S.PRODUCT_ID
	WHERE P.CATEGORY="ELECTRONICS");




SELECT * FROM ELECTRONICS_DETAILS;
SELECT * FROM CUSTOMERS;


CREATE VIEW CUSTOMERS_VIEW AS(
	SELECT * FROM CUSTOMERS);


SELECT * FROM CUSTOMERS_VIEW;

INSERT INTO CUSTOMERS VALUES ("C009","DHRUV","DELHI","DELHI","GOLD");




