CREATE DATABASE STORE;
USE STORE;


SELECT * FROM (
SELECT COUNT(*) ORDERS FROM SALES 
UNION
SELECT COUNT(*) CUSTOMERS FROM CUSTOMERS
UNION
SELECT COUNT(*) FROM PRODUCTS PRODUCTS )RESULT;



-- TOTAL ORDERS MADE BY UPI
SELECT
	COUNT(*) PAYMENT_MADE_BY_UPI
FROM(
	SELECT 
		* 
	FROM 
		SALES 
	WHERE 
		PAYMENT_MODE = "UPI")T;
        
        
        
        

-- ORDERS THOSE ARE GREATER ,THAN AVG QUANTITY
SELECT
	COUNT(*) RECORDS
FROM SALES
WHERE QUANTITY >
	(SELECT 
		AVG(QUANTITY) AVG_QUANTITY
	FROM SALES);
    
-- PRODUCT, SALES, CUSTOMERS
-- FIND CUSTOMERS WHO PURCHASED THE MOST EXPENSIVE PRODUCT

SELECT
	C.CUSTOMER_NAME,
    P.PRICE,
    P.PRODUCT_NAME
FROM SALES S
INNER JOIN CUSTOMERS C
ON C.CUSTOMER_ID = S.CUSTOMER_ID
INNER JOIN PRODUCTS P
ON P.PRODUCT_ID = S.PRODUCT_ID
WHERE P.PRODUCT_ID =
	(SELECT 
		PRODUCT_ID
	FROM PRODUCTS
	WHERE PRICE = 
		(SELECT 
			MAX(PRICE)
		FROM PRODUCTS));
        
SELECT
	CUSTOMER_ID,
    CUSTOMER_NAME
FROM CUSTOMERS 
WHERE CUSTOMER_ID IN(
	SELECT
		CUSTOMER_ID
	FROM SALES
	WHERE PRODUCT_ID = 
		(SELECT 
			PRODUCT_ID
		FROM PRODUCTS
		WHERE PRICE = 
			(SELECT 
				MAX(PRICE)
			FROM PRODUCTS)));
            
            
-- FIND THOSE CUSTOMERS WHO PURCHASED ELECTRONICS PRODUCTS
SELECT
	CUSTOMER_ID,
    CUSTOMER_NAME
FROM CUSTOMERS
WHERE CUSTOMER_ID
IN
	(SELECT
		CUSTOMER_ID
	FROM SALES
	WHERE PRODUCT_ID IN
		(SELECT
			PRODUCT_ID
		FROM PRODUCTS 
		WHERE
			CATEGORY = "Electronics"));


-- PRODUCTS SOLD MORE THAN THEIR AVERAGE QUANTITY.
SELECT
	PRODUCT_ID,
	PRODUCT_NAME,
    CATEGORY
FROM PRODUCTS
WHERE PRODUCT_ID IN
	(SELECT
		PRODUCT_ID
	FROM SALES S1
	WHERE QUANTITY >
		(SELECT
			AVG(QUANTITY) AVG_QTY
		FROM SALES S2
		WHERE S1.PRODUCT_ID = S2.PRODUCT_ID));
        
        
        
-- CUSTOMERS WHO PLACED AT LEAST ONE ORDER.

SELECT
	CUSTOMER_NAME
FROM CUSTOMERS C
WHERE EXISTS(
	SELECT 
		*
	FROM SALES S
    WHERE C.CUSTOMER_ID = S.CUSTOMER_ID
    );

-- CUSTOMERS WHO NEVER PLACED AT LEAST ONE ORDER.

SELECT
	CUSTOMER_NAME
FROM CUSTOMERS C
WHERE NOT EXISTS(
	SELECT 
		*
	FROM SALES S
    WHERE C.CUSTOMER_ID = S.CUSTOMER_ID
    );


-- PRODUCTS COSTLIER THAN AT LEAST ONE FURNITURE PRODUCTS.
SELECT
	PRODUCT_NAME
FROM PRODUCTS
WHERE PRICE > ANY
(	SELECT
		PRICE
	FROM PRODUCTS
	WHERE CATEGORY = "FURNITURE");

-- PRODUCTS COSTLIER THAN ALL FURNITURE PRODUCTS.

SELECT
	PRODUCT_NAME
FROM PRODUCTS
WHERE PRICE > ALL
(	SELECT
		PRICE
	FROM PRODUCTS
	WHERE CATEGORY = "FURNITURE");
    
    
-- SHOW EVERY PRODUCT WITH THE OVERALL AVERAGE PRICE
SELECT
	PRODUCT_NAME,
    PRICE,
    (SELECT 
		AVG(PRICE)
	FROM PRODUCTS) AS AVG_PRICE
FROM PRODUCTS;


-- AVERAGE QUANTITY SOLD BY CUSTOMERS
SELECT
	CUSTOMER_ID,
    AVG(TOTAL_QTY) AS AVG_QTY
FROM
    (SELECT
		CUSTOMER_ID,
		SUM(QUANTITY) AS TOTAL_QTY
	FROM SALES
	GROUP BY CUSTOMER_ID)T
GROUP BY CUSTOMER_ID;


-- CUSTOMERS WHOSE TOTAL QUANTITY IS ABOVE AVERAGE
SELECT
	CUSTOMER_ID,
	CUSTOMER_NAME
FROM CUSTOMERS
WHERE CUSTOMER_ID
IN
(	SELECT
		CUSTOMER_ID
	FROM
	(	SELECT
			CUSTOMER_ID,
			SUM(QUANTITY) AS TOTAL_QTY
		FROM SALES
		GROUP BY CUSTOMER_ID
		HAVING SUM(QUANTITY)>
			(SELECT
				AVG(TOTAL_QTY)
			FROM
			(SELECT
					CUSTOMER_ID,
					SUM(QUANTITY) AS TOTAL_QTY
				FROM SALES
				GROUP BY CUSTOMER_ID)T
			)
	)T
);
